#!/bin/bash
#-- sample small test

PHYSRAND=../imgdiff

BANKS=8
CAPACITY=2
LINKS=4
BSIZE=64
QDEPTH=64
XDEPTH=128
VAULTS=16
IMGSIZE=8480
WIDTH=128
STRIDE=4
DRAMS=20

echo "Executing : $PHYSRAND -b $BANKS -c $CAPACITY -l $LINKS -m $BSIZE -n 1 -q $QDEPTH -x $XDEPTH\
	-d $DRAMS -v $VAULTS -N $IMGSIZE  -W $WIDTH -T $STRIDE -S 65656"

$PHYSRAND -b $BANKS -c $CAPACITY -l $LINKS -m $BSIZE -n 1 -q $QDEPTH -x $XDEPTH\
	-d $DRAMS -v $VAULTS -N $IMGSIZE -W $WIDTH -T $STRIDE -S 65656
